services:
  jenkins:
    image: jenkins/jenkins:2.504.1-lts-jdk21
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    restart: on-failure
    networks:
      - jenkins_network
    volumes:
      - jenkins-home:/var/jenkins_home

networks:
  jenkins_network:
    name: jenkins_network

volumes:
  jenkins-home:
